version: '3.5'

networks:
  default:
    driver: bridge
    name: api

services:
  rinha-database:
    image: postgres
    container_name: rinha-database
    environment:
      - POSTGRES_USER=rinhabackend2024q1
      - POSTGRES_PASSWORD=rinhabackend2024q1
      - POSTGRES_DB=rinhabackend2024q1
    ports:
      - 5432:5432
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  rinha-api: &api
    build:
      context: .
      dockerfile: Dockerfile
    image: rinhabackend2024q1
    container_name: rinha-api
    environment:
      - DATABASE_HOSTNAME=rinha-database
      - DATABASE_NAME=rinhabackend2024q1
      - DATABASE_USER=rinhabackend2024q1
      - DATABASE_PASSWORD=rinhabackend2024q1
    ports:
      - 8080:8080
    depends_on:
      - rinha-database
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '200MB'

  rinha-api2:
    <<: *api
    container_name: rinha-api2
    ports:
      - 8081:8080

  rinha-proxy:
    image: nginx
    container_name: rinha-proxy
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - rinha-api
    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: "50MB"
