server:
  error:
    whitelabel:
      enabled: false

spring:
  main:
    banner-mode: "off"

  jackson:
    default-property-inclusion: NON_NULL

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://${DATABASE_HOSTNAME:127.0.0.1}:5432/${DATABASE_NAME:rinhabackend}
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:root}
    hikari:
      poolName: Hikari
      auto-commit: false