apiVersion: 1

datasources:
  - name: Prometheus
    isDefault: true
    type: prometheus
    access: proxy
    url: http://rinha-prometheus:9090
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://rinha-loki:3100
    editable: true
